// Leetcode:- https://leetcode.com/problems/find-the-difference/?envType=study-plan-v2&envId=programming-skills
// Leet Code Question no. 389
// Find the Difference Problem DSA
// Solution:- 

// 
// Hash Table; String; Bit Manipulation; Sorting Problem
// Easy

// T.C = o(n) 
// S.C = o(1) 
/**
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

/**
 Example:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
 */

public class FindTheDifference 
{
    public static void main(String[] args) 
    {
        FindTheDifference findDiff = new FindTheDifference();

        // Example strings
        String s = "abcd";
        String t = "abcde";

        // Finding the difference
        char result = findDiff.findTheDifference(s, t);

        // Printing the result
        System.out.println("The extra character is: " + result);
    }
    public char findTheDifference(String s, String t) 
    {
        // Initialize sum variables for both strings
        int sumS = 0, sumT = 0;

        // Calculate the sum of ASCII values of characters in string s
        for (int i = 0; i < s.length(); i++) {
            sumS += (int) s.charAt(i);
        }

        // Calculate the sum of ASCII values of characters in string t
        for (int i = 0; i < t.length(); i++) {
            sumT += (int) t.charAt(i);
        }

        // The difference in sums will give the ASCII value of the extra character
        return (char) (sumT - sumS);
    }
}
